namespace ConstructionMS.Domain.Entities;

/// <summary>
/// Source records that may own uploaded evidence. The allowlist is deliberately
/// closed so a client cannot invent an entity name and bypass source-level access.
/// </summary>
public static class EvidenceSourceTypes
{
    public const string ProjectProgressVerification = "ProjectProgressVerification";
    public const string GoodsReceipt = "GoodsReceipt";
    public const string GoodsReceiptTechnicalAcceptance = "GoodsReceiptTechnicalAcceptance";
    public const string MaterialUsageRecord = "MaterialUsageRecord";
    public const string SupplierInvoice = "SupplierInvoice";
    public const string Payment = "Payment";
    public const string PettyCashDisbursement = "PettyCashDisbursement";
    public const string PettyCashReconciliation = "PettyCashReconciliation";
    public const string OpeningPositionBatch = "OpeningPositionBatch";
    public const string MaterialReturn = "MaterialReturn";
    public const string MaterialReturnReceipt = "MaterialReturnReceipt";
    public const string MaterialIssueDisputeResolution = "MaterialIssueDisputeResolution";
    public const string MaterialCustodyCloseout = "MaterialCustodyCloseout";
    public const string ControlledCorrection = "ControlledCorrection";

    public static readonly IReadOnlySet<string> All = new HashSet<string>(StringComparer.Ordinal)
    {
        ProjectProgressVerification,
        GoodsReceipt,
        GoodsReceiptTechnicalAcceptance,
        MaterialUsageRecord,
        SupplierInvoice,
        Payment,
        PettyCashDisbursement,
        PettyCashReconciliation,
        OpeningPositionBatch,
        MaterialReturn,
        MaterialReturnReceipt,
        MaterialIssueDisputeResolution,
        MaterialCustodyCloseout,
        ControlledCorrection
    };
}

public static class EvidenceKinds
{
    public const string Photo = "Photo";
    public const string DeliveryNote = "DeliveryNote";
    public const string Inspection = "Inspection";
    public const string Invoice = "Invoice";
    public const string PaymentProof = "PaymentProof";
    public const string Receipt = "Receipt";
    public const string Other = "Other";

    public static readonly IReadOnlySet<string> All = new HashSet<string>(StringComparer.Ordinal)
    {
        Photo,
        DeliveryNote,
        Inspection,
        Invoice,
        PaymentProof,
        Receipt,
        Other
    };
}

/// <summary>
/// Immutable metadata for a validated file held in private storage. Storage keys
/// are generated by the server and never contain a client supplied file name.
/// </summary>
public sealed class EvidenceDocument
{
    public Guid Id { get; set; }
    public int ProjectId { get; set; }
    public Project Project { get; set; } = null!;
    public string StorageKey { get; set; } = string.Empty;
    public string OriginalFileName { get; set; } = string.Empty;
    public string ContentType { get; set; } = string.Empty;
    public long SizeBytes { get; set; }
    public string Sha256Hash { get; set; } = string.Empty;
    public int UploadedByUserId { get; set; }
    public User UploadedByUser { get; set; } = null!;
    public DateTime UploadedAt { get; set; }
    public EvidenceAttachment Attachment { get; set; } = null!;
}

/// <summary>
/// Immutable project-scoped link from one private document to one audited source
/// record. The service verifies the polymorphic source before this row is written.
/// </summary>
public sealed class EvidenceAttachment
{
    public long Id { get; set; }
    public Guid EvidenceDocumentId { get; set; }
    public EvidenceDocument EvidenceDocument { get; set; } = null!;
    public int ProjectId { get; set; }
    public Project Project { get; set; } = null!;
    public string SourceType { get; set; } = string.Empty;
    public long SourceId { get; set; }
    public string EvidenceKind { get; set; } = string.Empty;
    public int LinkedByUserId { get; set; }
    public User LinkedByUser { get; set; } = null!;
    public DateTime LinkedAt { get; set; }
}
